name:                 circuits-parser
version:              0.1.0.0
visibility:           public
id:                   circuits-parser-0.1.0.0-inplace
key:                  circuits-parser-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           tonyday567@gmail.com
author:               Tony Day
category:             parsing
abi:                  inplace
exposed:              True
exposed-modules:      Circuit.Parser Circuit.Parser.Token
import-dirs:
    /Users/tonyday567/haskell/circuits-parser/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-parser-0.1.0.0/build

library-dirs:
    /Users/tonyday567/haskell/circuits-parser/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-parser-0.1.0.0/build

library-dirs-static:
    /Users/tonyday567/haskell/circuits-parser/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-parser-0.1.0.0/build

dynamic-library-dirs:
    /Users/tonyday567/haskell/circuits-parser/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-parser-0.1.0.0/build

data-dir:             /Users/tonyday567/haskell/circuits-parser/.
hs-libraries:         HScircuits-parser-0.1.0.0-inplace
depends:
    base-4.22.0.0-1f90 bytestring-0.12.2.0-5637
    circuits-0.1.0.0-inplace clck-0.8.4-87884b8c containers-0.8-034d
    deepseq-1.5.1.0-f1e0 hrp-0.2.0.0-2c689568 prttyprntr-1.7.2-0b620892
    text-2.1.3-a2fa ths-1.2.1-49e3e16f

haddock-interfaces:
    /Users/tonyday567/haskell/circuits-parser/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-parser-0.1.0.0/doc/html/circuits-parser/circuits-parser.haddock

haddock-html:
    /Users/tonyday567/haskell/circuits-parser/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-parser-0.1.0.0/doc/html/circuits-parser
