name:                 circuits
version:              0.1.0.0
visibility:           public
id:                   circuits-0.1.0.0-inplace
key:                  circuits-0.1.0.0-inplace
license:              BSD-3-Clause
copyright:            Tony Day (c) 2025
maintainer:           tonyday567@gmail.com
author:               Tony Day
homepage:             https://github.com/tonyday567/circuits#readme
synopsis:             Free traced monoidal category over any base category
description:
    @circuits@ provides a free traced monoidal category construction over any base category.

category:             control
abi:                  inplace
exposed:              True
exposed-modules:      Circuit Circuit.Circuit Circuit.Hyper Circuit.Traced
import-dirs:
    /Users/tonyday567/haskell/circuits-parser/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-0.1.0.0/build

library-dirs:
    /Users/tonyday567/haskell/circuits-parser/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-0.1.0.0/build

library-dirs-static:
    /Users/tonyday567/haskell/circuits-parser/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-0.1.0.0/build

dynamic-library-dirs:
    /Users/tonyday567/haskell/circuits-parser/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-0.1.0.0/build

data-dir:             /Users/tonyday567/haskell/circuits-parser/../circuits/.
hs-libraries:         HScircuits-0.1.0.0-inplace
depends:
    base-4.22.0.0-1f90 prfnctrs-5.6.3-04fd684a ths-1.2.1-49e3e16f

haddock-interfaces:
    /Users/tonyday567/haskell/circuits-parser/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-0.1.0.0/doc/html/circuits/circuits.haddock

haddock-html:
    /Users/tonyday567/haskell/circuits-parser/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-0.1.0.0/doc/html/circuits
